### ISSUE TITLE
Exception while parsing diff

### ISSUE THREAD

**Issue by maxbrunsfeld** [kuychaco/what-the-diff#3]
When parsing the following diff:

```
diff --cc modified-on-both-ours.txt
index 5b7855c,1353022..0000000
--- modified-on-both-ours.txt
+++ modified-on-both-ours.txt
diff --cc modified-on-both-theirs.txt
index 5b7855c,1353022..0000000
--- modified-on-both-theirs.txt
+++ modified-on-both-theirs.txt
@@@ -1,1 -1,1 +1,5 @@@
++<<<<<<< HEAD
 +master modification
++=======
+ branch modification
++>>>>>>> origin/branch
```

I'm seeing this exception:

```
TypeError: Cannot set property 'status' of null
    at peg$c2 (/Users/max/github/github/node_modules/what-the-diff/lib/parser.js:147:24)
    at peg$parsemerge_conflict_diff (/Users/max/github/github/node_modules/what-the-diff/lib/parser.js:516:16)
    at peg$parsediff (/Users/max/github/github/node_modules/what-the-diff/lib/parser.js:434:10)
    at peg$parsediffs (/Users/max/github/github/node_modules/what-the-diff/lib/parser.js:406:10)
    at Object.peg$parse [as parse] (/Users/max/github/github/node_modules/what-the-diff/lib/parser.js:1791:16)
    at parse (/Users/max/github/github/node_modules/what-the-diff/index.js:6:21)
```

**Comment by BinaryMuse** [comment]
After recent changes the new error is:

```
{ start: { offset: 127, line: 5, column: 1 },
  end: { offset: 128, line: 5, column: 2 } }
SyntaxError: Expected "@@ -" or "@@@ -" but "d" found.
    at peg$buildStructuredError (/Users/mtilley/src/sandbox/node_modules/what-the-diff/lib/parser.js:379:12)
    at Object.peg$parse [as parse] (/Users/mtilley/src/sandbox/node_modules/what-the-diff/lib/parser.js:1940:11)
    at Object.parse (/Users/mtilley/src/sandbox/node_modules/what-the-diff/index.js:6:21)
    at repl:1:3
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
```
